service: sample-app
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.8
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  hello:
    handler: api.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{path+}
          method: ANY

package:
  patterns:
    - '!**' # すべてのファイルをexclude
    - 'api/**' # fastapiのソースコードをinclude

custom:
  pythonRequirements:
    dockerizePip: true # deploy時のパッケージングの際にpythonライブラリのビルドをdockerで行う設定
    layer: true # レイヤーを作成する

plugins:
  - serverless-python-requirements
